:recycle: expose prisma cloud docker image param
The current execution is failing with the following error message:

Run echo "Executing command docker run --rm -u root -v $(pwd):$(pwd) -w $(pwd) -v /var/run/docker.sock:/var/run/docker.sock -e JOB_NAME=Harmony/chatgpt-lambda-record-user-actions -e JOB_URL=https://git.viasat.com/Harmony/chatgpt-lambda-record-user-actions/actions/runs/222984 ***.docker.artifactory.viasat.com/devsecops/client/runtime/twistcli:latest images scan --address https://twistlock.infosec.viasat.io --project Container Services --user *** -*** --details --output-file ${REPORT_FILE_NAME} viasat-ai-platform.docker.artifactory.viasat.com/chatgpt/users/actions/record-user-actions-lambda:6e1f37d46ef21cb71e5f7c60ab01057a6e81cbe6"
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
Error: Process completed with exit code 126.

This is because this docker image is older and failing to execute. Users should provide the version number to their docker image to make sure we have the appropriate docker image.
This should resolve the issue as the default value should fix the build