:octocat: :recycle: replace docker:// gha linter with problem matcher
Since the Viasat docker hub registry proxy, the run fails.
Bypassing it by using the regular run.

Error: .github#L1
docker://dockerhub.docker.artifactory.viasat.com/rhysd/actionlint:1.6.26 is not allowed to be used in seceng-devsecops-platform/devsecops-platform-github-workflows. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: ansible/*, aws-actions/*, azure/*, docker/*, docker://ghcr.io/github/*, github/*, github/*, hashicorp/*, ruby/*, slackapi/*.

* Adding also the problem matcher