:octocat: remove debug message from release workflow
Run echo "latest-release={
  echo "latest-release={
    "outputs": {
      "status": "200",
      "headers": "{\n  \"access-control-allow-origin\": \"*\",\n  \"access-control-expose-headers\": \"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset\",\n  \"cache-control\": \"private, max-age=60, s-maxage=60\",\n  \"connection\": \"close\",\n  \"content-encoding\": \"gzip\",\n  \"content-security-policy\": \"default-src 'none'\",\n  \"content-type\": \"application/json; charset=utf-8\",\n  \"date\": \"Tue, 04 Jul 2023 06:10:50 GMT\",\n  \"etag\": \"W/\\\"949d395c1e33049751f321caecbc328e66e215abd94a34463ae1e7c34aa1157d\\\"\",\n  \"last-modified\": \"Tue, 04 Jul 2023 05:56:15 GMT\",\n  \"referrer-policy\": \"origin-when-cross-origin, strict-origin-when-cross-origin\",\n  \"server\": \"GitHub.com\",\n  \"strict-transport-security\": \"max-age=31536000; includeSubdomains\",\n  \"transfer-encoding\": \"chunked\",\n  \"vary\": \"Accept, Authorization, Cookie, X-GitHub-OTP\",\n  \"x-accepted-oauth-scopes\": \"repo\",\n  \"x-content-type-options\": \"nosniff\",\n  \"x-frame-options\": \"deny\",\n  \"x-github-enterprise-version\": \"3.8.4\",\n  \"x-github-media-type\": \"github.v3; format=json\",\n  \"x-github-request-id\": \"5a664d77-96ad-463d-bf81-e06fcd944e7b\",\n  \"x-oauth-scopes\": \"admin:org, admin:org_hook, admin:repo_hook, repo\",\n  \"x-runtime-rack\": \"0.045576\",\n  \"x-xss-protection\": \"0\"\n}",
      "data": "{\n  \"url\": \"https://git.viasat.com/api/v3/repos/seceng-devsecops-platform/devsecops-platform-artifactory-manager/releases/57441\",\n  \"assets_url\": \"https://git.viasat.com/api/v3/repos/seceng-devsecops-platform/devsecops-platform-artifactory-manager/releases/57441/assets\",\n  \"upload_url\": \"https://git.viasat.com/api/uploads/repos/seceng-devsecops-platform/devsecops-platform-artifactory-manager/releases/57441/assets{?name,label}\",\n  \"html_url\": \"https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/releases/tag/v1.0.0-RC1\",\n  \"id\": 57441,\n  \"author\": {\n    \"login\": \"mdesales\",\n    \"id\": 6318,\n    \"node_id\": \"MDQ6VXNlcjYzMTg=\",\n    \"avatar_url\": \"https://avatars.git.viasat.com/u/6318?\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://git.viasat.com/api/v3/users/mdesales\",\n    \"html_url\": \"https://git.viasat.com/mdesales\",\n    \"followers_url\": \"https://git.viasat.com/api/v3/users/mdesales/followers\",\n    \"following_url\": \"https://git.viasat.com/api/v3/users/mdesales/following{/other_user}\",\n    \"gists_url\": \"https://git.viasat.com/api/v3/users/mdesales/gists{/gist_id}\",\n    \"starred_url\": \"https://git.viasat.com/api/v3/users/mdesales/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://git.viasat.com/api/v3/users/mdesales/subscriptions\",\n    \"organizations_url\": \"https://git.viasat.com/api/v3/users/mdesales/orgs\",\n    \"repos_url\": \"https://git.viasat.com/api/v3/users/mdesales/repos\",\n    \"events_url\": \"https://git.viasat.com/api/v3/users/mdesales/events{/privacy}\",\n    \"received_events_url\": \"https://git.viasat.com/api/v3/users/mdesales/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  },\n  \"node_id\": \"MDc6UmVsZWFzZTU3NDQx\",\n  \"tag_name\": \"v1.0.0-RC1\",\n  \"target_commitish\": \"main\",\n  \"name\": \"v1.0.0-RC1\",\n  \"draft\": false,\n  \"prerelease\": false,\n  \"created_at\": \"2023-07-04T01:44:07Z\",\n  \"published_at\": \"2023-07-04T05:22:19Z\",\n  \"assets\": [],\n  \"tarball_url\": \"https://git.viasat.com/api/v3/repos/seceng-devsecops-platform/devsecops-platform-artifactory-manager/tarball/v1.0.0-RC1\",\n  \"zipball_url\": \"https://git.viasat.com/api/v3/repos/seceng-devsecops-platform/devsecops-platform-artifactory-manager/zipball/v1.0.0-RC1\",\n  \"body\": \"New release notes...\\r\\n\\r\\n## What's Changed\\r\\n* RC: Add release management workflows by @mdesales in https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/pull/1\\r\\n* :octocat: :recycle: just add emoji for DevSecOps Platform releases by @mdesales in https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/pull/2\\r\\n* :octocat: :recycle: Add required token as the call failed by @mdesales in https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/pull/3\\r\\n* :bulb: :whale: just add documentation on compose by @mdesales in https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/pull/4\\r\\n\\r\\n## New Contributors\\r\\n* @mdesales made their first contribution in https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/pull/1\\r\\n\\r\\n**Full Changelog**: https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/commits/v1.0.0-RC1\",\n  \"mentions_count\": 1\n}"
    },
    "outcome": "success",
    "conclusion": "success"
  }"
  shell: /usr/bin/bash -e {0}
  env:
    DEFAULT_DOCKER_IMAGE_VERSION: 91eafb6291fa0104061fa27a2ccccdf3639a633a
    BRANCH_TAG: main
    BRANCH_TAG_FOR_VERSION: main
    GIT_SHORT_SHA: 91eafb6
    BRANCH_SHA_TAG: 91eafb6-main
    NEXT_PUBLIC_APP_VERSION: 91eafb6-main
    BUILD_JOB_NAME: https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/actions/runs/252707
    BUILD_JOB_URL: https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/actions/runs/252707
    BUILD_DATE_TIME: 2023-07-04 06:07:50 UTC
    JOB_TIMESTAMP: 1688451050
    COMMITTER_NAME: DeSales Jr, Marcello
    COMMITTER_EMAIL: Marcello.DeSales@viasat.com
/runner/_work/_temp/c1785dc3-df2f-460a-9c48-c94e64f5fe13.sh: line 5: unexpected EOF while looking for matching `''
Error: Process completed with exit code 2.