:bug: :octocat: release notes generator broke
Warning: Unexpected input(s) 'name', 'tag_name', 'body', valid inputs are ['route', 'mediaType']
Run octokit/request-action@v2.x
  with:
    route: POST /repos/Harmony/azure-chatgpt-spa-service/releases
    name: v1.0.0-RC9
    tag_name: v1.0.0-RC9
    body: <!-- Release notes generated using configuration in .github/release.yml at develop -->
  
  ## What's Changed
  ### 👽 Middleware
  * Bug Fix - Fetch OAuth2 userinfo and cache user_id in localStorage by @kenguyen in https://git.viasat.com/Harmony/azure-chatgpt-spa-service/pull/133
  ### 🧮 Lambda Functions
  * RC: Bug fixes and features for pilot using .com by @mdesales in https://git.viasat.com/Harmony/azure-chatgpt-spa-service/pull/134
  
  
  **Full Changelog**: https://git.viasat.com/Harmony/azure-chatgpt-spa-service/compare/v1.0.0-RC8...v1.0.0-RC9
    mediaType: {}
  env:
    GITHUB_TOKEN: ***
Error: end of the stream or a document separator is expected (5:1)

 2 | 
 3 | ## What's Changed
 4 | ### 👽 Middleware
 5 | * Bug Fix - Fetch OAuth2 userinf ...
-----^
 6 | ### 🧮 Lambda Functions
 7 | * RC: Bug fixes and features for ...