:octocat: :bug: Add required token for the API action
Run octokit/request-action@v2.x
  with:
    route: GET /repos/seceng-devsecops-platform/devsecops-platform-artifactory-manager/releases/latest
    mediaType: {}
  env:
    DEFAULT_DOCKER_IMAGE_VERSION: 6668299b50be9dda922f0746ba6222e7346f6e90
    BRANCH_TAG: main
    BRANCH_TAG_FOR_VERSION: main
    GIT_SHORT_SHA: 6668299
    BRANCH_SHA_TAG: 6668299-main
    NEXT_PUBLIC_APP_VERSION: 6668299-main
    BUILD_JOB_NAME: https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/actions/runs/252579
    BUILD_JOB_URL: https://git.viasat.com/seceng-devsecops-platform/devsecops-platform-artifactory-manager/actions/runs/252579
    BUILD_DATE_TIME: 2023-07-04 01:07:58 UTC
    JOB_TIMESTAMP: 1688434078
    COMMITTER_NAME: DeSales Jr, Marcello
    COMMITTER_EMAIL: Marcello.DeSales@viasat.com
Error: [@octokit/auth-action] `GITHUB_TOKEN` variable is not set. It must be set on either `env:` or `with:`. See https://github.com/octokit/auth-action.js#createactionauth