:bug: :octocat: fix lint/test code inputs _ to -
This was missing during the patch creation and broke  https://git.viasat.com/Harmony/chatgpt-lambda-record-user-auth/runs/1091849?check_suite_focus=true

CURRENT_DIR=/runner/_work/chatgpt-lambda-record-user-auth/chatgpt-lambda-record-user-auth
stat /runner/_work/chatgpt-lambda-record-user-auth/chatgpt-lambda-record-user-auth/-f: no such file or directory
Error: Process completed with exit code 14.