:bug: fix support for buildx with latest docker buildx
The build fails with latest version because the buildx action
doesn't have a context. More context on the error when the runner
was exposed as param:

   * https://github.com/docker/setup-buildx-action/issues/105#issuecomment-910928571
   * https://github.com/docker/buildx/issues/413#issuecomment-710656847

Run seceng-devsecops-platform/docker-setup-buildx-action@master
Docker info
  /usr/local/bin/docker version
  Client:
   Version:           20.10.23
   API version:       1.41
   Go version:        go1.18.10
   Git commit:        7155243
   Built:             Thu Jan 19 17:30:35 2023
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true

  Server: Docker Engine - Community
   Engine:
    Version:          24.0.2
    API version:      1.43 (minimum version 1.12)
    Go version:       go1.20.4
    Git commit:       659604f
    Built:            Thu May 25 21:35:04 2023
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          v1.7.1
    GitCommit:        1677a17964311325ed1c31e2c0a3589ce6d5c30d
   runc:
    Version:          1.1.7
    GitCommit:        v1.1.7-0-g860f061
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /usr/local/bin/docker info
  Client:
   Context:    default
   Debug Mode: false
   Plugins:
    compose: Docker Compose (Docker Inc., v2.16.0)

  Server:
   Containers: 0
    Running: 0
    Paused: 0
    Stopped: 0
   Images: 2
   Server Version: 24.0.2
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: true
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 1677a17964311325ed1c31e2c0a3589ce6d5c30d
   runc version: v1.1.7-0-g860f061
   init version: de40ad0
   Security Options:
    apparmor
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 5.19.0-1017-aws
   Operating System: Alpine Linux v3.18 (containerized)
   OSType: linux
   Architecture: x86_64
   CPUs: 16
   Total Memory: 61.37GiB
   Name: seceng-devsecops-platform-org-runners-fffml-pl8ft
   ID: 6ab2d577-26b9-404c-92d8-a8fb9c381e6f
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Registry: https://index.docker.io/v1/
   Labels:
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Registry Mirrors:
    https://dockerhub.docker.artifactory.viasat.com/
   Live Restore Enabled: false
   Product License: Community Engine

Download and install buildx
Buildx version
Creating a new builder instance
  /usr/local/bin/docker buildx create --name builder-0f3650a9-8b14-49e3-bdfe-a80def3d152b --driver docker-container --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
  ERROR: could not create a builder instance with TLS data loaded from environment. Please use `docker context create <context-name>` to create a context for current environment and then create a builder instance with `docker buildx create <context-name>`
  Error: The process '/usr/local/bin/docker' failed with exit code 1