:recycle: :bug: Use GHA runner with label "dind"
The servers are not running with docker for whatever reason.
Since viarise might be changing these, I have deployed
a set of runners.

time="2023-04-12T07:36:07Z" level=warning msg="The \"NEXT_PUBLIC_APP_VERSION\" variable is not set. Defaulting to a blank string."
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
Error: Process completed with exit code 125.

This uses the "dind" deployment at the DevSecOps platform.